export const USDC_CONTRACT_ADDRESS =
  "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA";
export const VOUCHER_TOKEN_CONTRACT_ADDRESS =
  "CAFJ5DGQKIBMMWIKLLLKYL57DRF2HGYEAG3WPT6LLJITIFDQZNHGFQKA";
export const VOUCHER_ESCROW_CONTRACT_ADDRESS =
  "CBSJBFLGPRK5HW3BACEZMTIXUI7QMPV4YKX5WTTAKYOIL72SQAYBPDCM";
